# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCc < Formula
  desc "A git extension to help write conventional commits."
  homepage "https://github.com/skalt/git-cc"
  version "0.0.11"
  license "Indie Code Catalog Standard Deal >= 4.1"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SKalt/git-cc/releases/download/v0.0.11/git-cc_0.0.11_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "72fd80a71d1fce46e78c99b949c12237772a2d1114dc17b22fc22b5dba6f07bd"

      def install
        bin.install "git-cc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SKalt/git-cc/releases/download/v0.0.11/git-cc_0.0.11_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "baf7e8693d72c4bade8e24ecd24f20fe82387f1afbfbcacef4d749ce7a7696bb"

      def install
        bin.install "git-cc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/SKalt/git-cc/releases/download/v0.0.11/git-cc_0.0.11_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e779e6815f999b36283e66cc84f46c2926cabec2b342e830a1e12092f949aa05"

      def install
        bin.install "git-cc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SKalt/git-cc/releases/download/v0.0.11/git-cc_0.0.11_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d359fb1e085351807038e4a8cd92e86b28c55ff817962f35db076658be5fe4e4"

      def install
        bin.install "git-cc"
      end
    end
  end
end
